# Generated by Django 3.0.8 on 2020-07-25 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200725_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='page',
            new_name='age',
        ),
    ]
