# Generated by Django 3.0.8 on 2020-08-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCalculatorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_price', models.IntegerField()),
                ('tax_rate', models.DecimalField(decimal_places=1, max_digits=9)),
                ('down_payment', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=9)),
                ('loan_term_in_years', models.IntegerField()),
                ('trade_in_value', models.IntegerField()),
            ],
        ),
    ]
