# Generated by Django 3.0.8 on 2020-08-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_carcalculatormodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarCalculatorModel',
        ),
    ]
