# Generated by Django 3.0.8 on 2020-08-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200813_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcalculatormodel',
            name='car_name',
            field=models.CharField(max_length=40),
        ),
    ]
